server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: naishuawang-next-backend
  #  数据库配置(注意在哪一级）:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/naishuawang
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 2000
    # password:
  # Elasticsearch 配置
  elasticsearch:
    uris: http://localhost:9200
    username:
    password:

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环节打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 逻辑删除配置
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
#  hotkey配置
hotkey:
  app-name: naishuawang
  caffeine-size: 10000
  push-period: 1000
  etcd-server: http://localhost:2379

#  knife4j接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.chiu.naishuawangnextbackend.controller


# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: naishuawang
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录（为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true


